### ISSUE TITLE
Error while running 'yarn test'

### ISSUE THREAD

**Issue by rakesh-k** [lifeomic/lambda-typescript-webpack-babel-starter#9]
I am running into the following issue when running the `yarn test`:
```
$ yarn lint && yarn compile-test
$ tslint --project tsconfig.json 'src/**/*.ts' 'test/**/*.ts'
$ rm -rf work/dist-test && tsc -p tsconfig-test.json && cp package.json work/dist-test
$ nyc ava 'work/dist-test/test/unit/**/*.test.js'
/home/rakesh/work/lambda-typescript-webpack-babel-starter/work/dist-test/test/unit/util/invokeLambdaHandler.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";var cov_r391bghdh=function(){var path="/home/rakesh/work/lambda-typescript-webpack-babel-starter/work/dist-test/test/unit/util/invokeLambdaHandler.js",hash="6b63568082f328701ed5be87cc30571cc1d54811",global=new Function('return this')(),gcv="__coverage__",coverageData={path:"/home/rakesh/work/lambda-typescript-webpack-babel-starter/work/dist-test/test/unit/util/invokeLambdaHandler.js",statementMap:{"0":{start:{line:2,column:0},end:{line:2,column:62}},"1":{start:{line:4,column:4},end:{line:11,column:7}},"2":{start:{line:5,column:8},end:{line:10,column:11}},"3":{start:{line:6,column:12},end:{line:8,column:13}},"4":{start:{line:7,column:16},end:{line:7,column:35}},"5":{start:{line:9,column:12},end:{line:9,column:28}},"6":{start:{line:13,column:0},end:{line:13,column:38}}},fnMap:{"0":{name:"invokeLambdaHandler",decl:{start:{lin

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at runInThisContext (vm.js:97:10)
    at Object.vm.runInThisContext (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:142:16)
    at Module._compile (module.js:542:28)
    at Module.replacementCompile (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at extensions.(anonymous function) (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/require-precompiled/index.js:16:3)
    at /home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rakesh/work/lambda-typescript-webpack-babel-starter/work/dist-test/test/unit/lambda-func2.test.js:4:17)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at extensions.(anonymous function) (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/require-precompiled/index.js:13:11)
    at /home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/ava/lib/test-worker.js:56:1)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at runMain (/home/rakesh/.node-spawn-wrap-21085-c01a5f80e4f5/node:68:10)
    at Function.<anonymous> (/home/rakesh/.node-spawn-wrap-21085-c01a5f80e4f5/node:171:5)
    at Object.<anonymous> (/home/rakesh/work/lambda-typescript-webpack-babel-starter/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at /home/rakesh/.node-spawn-wrap-21085-c01a5f80e4f5/node:178:8
    at Object.<anonymous> (/home/rakesh/.node-spawn-wrap-21085-c01a5f80e4f5/node:181:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

  4 exceptions

  ✖ work/dist-test/test/unit/lambda-func1.test.js exited with a non-zero exit code: 1

  ✖ work/dist-test/test/unit/lambda-aws-sts-caller-identity.test.js exited with a non-zero exit code: 1

  ✖ work/dist-test/test/unit/util.test.js exited with a non-zero exit code: 1

  ✖ work/dist-test/test/unit/lambda-func2.test.js exited with a non-zero exit code: 1
````

**Comment by ctdio** [comment]
@rakesh-k Looks like a node version issue to me, looks like you are using a version that does not support `async/await`. Since this project builds lambdas that use 6.10, it should work for a 6.10 environment. PR #10 should fix this problem for you.

cc @philidem

**Comment by philidem** [comment]
Thanks @charlieduong94 for the fix. I hadn't anticipated using an old version of node.js to run the tests. Using `babel-register` at runtime will transpile the JavaScript to a version that can be loaded by older versions of nodejs.
